name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: docker://ghcr.io/kivy/buildozer:latest

        with:
          args: buildozer android debug